### ISSUE TITLE
Virtual Machine docker

### ISSUE THREAD

**Issue by hozansahin** [aliuosio/magento2docker#1]
Hello, 
How can run on Virtual Machine docker install, 
It's always redirecting to localhost in Nginx config. how can i use this on my server?
can you help with this I don't know much about Nginx

https://github.com/aliuosio/magento2docker/blob/55ec498d5616b2002afe7dd45b5fbf8f94a9c5de/.docker/config/nginx/default.conf#L7-L20

**Comment by aliuosio** [comment]
Have not tried it with a virtual machine. 
But you have to run the 
/usr/local/bin/start in the docker container and the IP will be set in the Magento 2 DB and displayed to you in the console.
This seems to be loaded after the Nginx config.
Tell me what happens?

**Comment by hozansahin** [comment]
bruh

**Comment by aliuosio** [comment]
> bruh

What's that? A troll?
